apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          env:
            - name: GF_INSTALL_PLUGINS
              value: "grafana-clock-panel,grafana-simple-json-datasource"
          volumeMounts:
            - name: grafana-grafana-ini
              mountPath: /etc/grafana/grafana.ini
              subPath: grafana.ini
            - name: grafana-config-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-config-dashboards
              mountPath: /etc/grafana/provisioning/dashboards
            - name: grafana-data
              mountPath: /var/lib/grafana
            - name: grafana-dashboards-mezo
              mountPath: /var/lib/grafana/dashboards
      volumes:
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-pvc
        - name: grafana-dashboards-mezo
          configMap:
            name: grafana-dashboards-mezo
        - name: grafana-config-datasources
          configMap:
            name: grafana-config
            items:
              - key: datasources.yaml
                path: datasources.yaml
        - name: grafana-config-dashboards
          configMap:
            name: grafana-config
            items:
              - key: dashboards.yaml
                path: dashboards.yaml
        - name: grafana-grafana-ini
          configMap:
            name: grafana-config
            items:
              - key: grafana.ini
                path: grafana.ini
