apiVersion: v1
kind: Service
metadata:
  name: metrics-scraper
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "mezo-staging-monitoring-external-ip"
    kubernetes.io/ingress.class: "gce"
spec:
  selector:
    app: metrics-scraper
  ports:
    - port: 2112
      targetPort: 2112
  type: ClusterIP
