image: us-central1-docker.pkg.dev/mezo-test-420708/mezo-staging-docker-public/mezod
# tag: v0.2.0-rc1 # use version from chart

env:
  NETWORK: testnet
  PUBLIC_IP: "34.134.59.27" # mezo-staging-node-0-external-ip
  MEZOD_MONIKER: "mezo-node-0"

secret: "mezo-node-0" # created manually

storage:
  className: "premium-rwo"
  size: "100Gi"
  useDataSource:
    enabled: true
    apiGroup: ""
    kind: PersistentVolumeClaim
    name: "mezo-node-data-mezo-node-0-0"

service:
  public:
    loadBalancerIP: "34.134.59.27" # same as PUBLIC_IP

labels:
  app: mezo
  type: node
  id: "0"

maintenanceMode: false
