image: us-central1-docker.pkg.dev/mezo-test-420708/mezo-staging-docker-public/mezod
# tag: ""

env:
  NETWORK: testnet
  PUBLIC_IP: "104.198.64.215" # mezo-staging-node-1-external-ip
  MEZOD_MONIKER: "mezo-node-1"

secret: "mezo-node-1" # created manually

storage:
  className: "premium-rwo"
  size: "100Gi"
  useDataSource:
    enabled: true
    apiGroup: ""
    kind: PersistentVolumeClaim
    name: "mezo-node-data-mezo-node-1-0"

service:
  public:
    loadBalancerIP: "104.198.64.215" # same as PUBLIC_IP

labels:
  app: mezo
  type: node
  id: "1"

maintenanceMode: false
