image: us-central1-docker.pkg.dev/mezo-test-420708/mezo-staging-docker-public/mezod
# tag: ""

env:
  NETWORK: testnet
  PUBLIC_IP: "34.70.22.86" # mezo-staging-node-4-external-ip
  MEZOD_MONIKER: "mezo-node-4"

secrets:
  credentials: "mezo-node-4" # created manually

storage:
  className: "premium-rwo"
  size: "100Gi"
  useDataSource:
    enabled: true
    apiGroup: ""
    kind: PersistentVolumeClaim
    name: "mezo-node-data-mezo-node-4-0"

service:
  public:
    loadBalancerIP: "34.70.22.86" # same as PUBLIC_IP

labels:
  app: mezo
  type: node
  id: "4"

maintenanceMode: false
