image: us-central1-docker.pkg.dev/mezo-test-420708/mezo-staging-docker-public/mezod
# tag: ""

env:
  NETWORK: testnet
  PUBLIC_IP: "104.197.235.84" # mezo-staging-node-2-external-ip
  MEZOD_MONIKER: "mezo-node-2"

secrets:
  credentials: "mezo-node-2" # created manually

storage:
  className: "premium-rwo"
  size: "100Gi"
  useDataSource:
    enabled: true
    apiGroup: ""
    kind: PersistentVolumeClaim
    name: "mezo-node-data-mezo-node-2-0"

service:
  public:
    loadBalancerIP: "104.197.235.84" # same as PUBLIC_IP

labels:
  app: mezo
  type: node
  id: "2"

maintenanceMode: false
