apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- ingress.yaml

patches:
- path: metrics-scraper/service-patch.yaml
- path: grafana/deployement-patch.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: staging

namePrefix: staging-

namespace: monitoring
