helmDefaults:
  kubeContext: gke_mezo-test-420708_us-central1_mezo-staging-gke-cluster

repositories:
  - name: mezo-org
    url: https://mezo-org.github.io/validator-kit

releases:
  - name: mezo-node-0
    installed: true
    namespace: default
    chart: mezo-org/mezod
    version: 0.0.10
    values:
      - ./values/mezo-node-common.yaml
      - ./values/mezo-node-0.yaml

  - name: mezo-node-1
    installed: true
    namespace: default
    chart: mezo-org/mezod
    version: 0.0.10
    values:
      - ./values/mezo-node-common.yaml
      - ./values/mezo-node-1.yaml

  - name: mezo-node-2
    installed: true
    namespace: default
    chart: mezo-org/mezod
    version: 0.0.10
    values:
      - ./values/mezo-node-common.yaml
      - ./values/mezo-node-2.yaml

  - name: mezo-node-3
    installed: true
    namespace: default
    chart: mezo-org/mezod
    version: 0.0.10
    values:
      - ./values/mezo-node-common.yaml
      - ./values/mezo-node-3.yaml

  - name: mezo-node-4
    installed: true
    namespace: default
    chart: mezo-org/mezod
    version: 0.0.10
    values:
      - ./values/mezo-node-common.yaml
      - ./values/mezo-node-4.yaml
