name = "mezo-faucet"
main = "./src/index.ts"
compatibility_date = "2022-10-10"
dev.port = 8000
node_compat = true
logpush = true

# Development
[vars]
MEZO_API_URL = "http://localhost:8545"
AMOUNT_BTC = "0.001"

# Staging
[env.staging]
route = { pattern = "faucet.test.mezo.org", custom_domain = true }

[env.staging.vars]
MEZO_API_URL = "http://mezo-node-0.test.mezo.org:8545"
AMOUNT_BTC = "0.001"