name: E2E Test Release
# The workflow runs a custom `make test-e2e` command for pull-requests
# targeting the `release/**` branches and for pushes to those branches, if
# certain files were modified.
on:
  pull_request:
    branches:
      - release/**
  push:
    branches:
      - release/**

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'
          check-latest: true
      - uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.sol
            **/**.go
            go.mod
            go.sum
      - name: Test E2E
        run: |
          make test-e2e
        if: env.GIT_DIFF
