name: E2E Test
# The workflow runs a custom `make test-e2e` command for pull-requests targeting
# the `main` branch and for pushes to this branch, if certain files were
# modified.
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'
          check-latest: true
      - uses: actions/checkout@v4
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            app/app.go
            app/upgrades/*
            go.mod
            go.sum
            tests/e2e/*
      - name: Test E2E
        env:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
        run: |
          make test-e2e
        if: env.GIT_DIFF

