
# TODO: The workflow, in conjunction with the Makefile config, was used by Evmos
# to automate the process of creating and publishing releases for the
# `github.com/evmos/evmos` Go project. We need to decide if we want to use
# similar release config for our project as the one used for
# `github.com/evmos/evmos` and adjust the workflow and Makefile config
# accordingly.

# name: goreleaser

# on:
#   push:
#     tags:
#       - "v*.*.*"
# jobs:
#   goreleaser:
#     runs-on: ubuntu-latest
#     environment: release
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           submodules: true
#       - name: Set up Go
#         uses: actions/setup-go@v3
#         with:
#           go-version: '1.20'
#           check-latest: true
#       - name: release dry run
#         run: make release-dry-run
#       - name: setup release environment
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         run: |-
#           echo 'GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}' > .release-env
#       - name: release publish
#         run: make release
