name: "Pull Request Labeler"
# The workflow automatically labels new pull requests based on the paths of
# files being changed or the branch name. The rules for the labeling are
# specified in the `.github/labeler.yml` file.
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
