name: Run Gosec
# The workflow runs a security scan on the Go code. The security scan is done
# using `cosmos/gosec@master` action which got forked from
# https://github.com/securego/gosec and introduced some new rules targeting the
# Cosmos-SDK.
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  Gosec:
    permissions:
      security-events: write
      contents: read

    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Get Diff
        uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/*.go
            go.mod
            go.sum
      - name: Run Gosec Security Scanner
        uses: cosmos/gosec@master
        with:
          # we let the report trigger content trigger a failure using the GitHub Security features.
          args: "-no-fail -fmt sarif -out results.sarif ./..."
        if: "env.GIT_DIFF_FILTERED != ''"
