name: Solhint
# The workflow runs the Solhint linter for Solidity contracts. It runs when
# changes are made to files within the `contracts` directory.
on:
  pull_request:
    paths:
      - "contracts/**"

jobs:
  solhint:
    name: runner / solhint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - run: npm install -g solhint
      - run: solhint --version
      - run: solhint 'contracts/**/*.sol'
