name: Tests
# The workflow runs unit tests and generates a coverage report for Go and
# Solidity code. It triggers on pull requests and pushes to the main branch or
# any branch that starts with `release/`.
on:
  pull_request:
  push:
    branches:
      - main
      - release/**

jobs:
  test-unit-cover:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          check-latest: true
      - uses: actions/checkout@v4
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.sol
            **/**.go
            go.mod
            go.sum
      - name: Test and Create Coverage Report
        run: |
          make test-unit-cover
        if: env.GIT_DIFF
